# Generated by Django 3.2.13 on 2022-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('email_auth', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
