# Generated by Django 3.2.13 on 2022-06-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('damage', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('road_address', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Lane',
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_id', models.ForeignKey(db_column='lane_id', on_delete=django.db.models.deletion.CASCADE, to='Mainapp.lane')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Scrap',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('report_images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('lane_id', models.ForeignKey(db_column='lane_id', on_delete=django.db.models.deletion.CASCADE, related_name='lane', to='Mainapp.lane')),
            ],
        ),
    ]
